import type { ITheme } from '@xterm/xterm';

export interface TerminalTheme {
  id: string;
  name: string;
  accent: string; // UI accent color (header border, etc.)
  description: string;
  xterm: ITheme;
}

export const TERMINAL_THEMES: TerminalTheme[] = [
  {
    id: 'termimate-dark',
    name: 'Termimate Dark',
    accent: '#7c6af5',
    description: 'Deep space with vibrant neons',
    xterm: {
      background: '#0d0d0f',
      foreground: '#e2dfe8',
      cursor: '#7c6af5',
      cursorAccent: '#0d0d0f',
      selectionBackground: 'rgba(124, 106, 245, 0.25)',
      selectionForeground: '#ffffff',
      black: '#1a1a1f',
      red: '#ff6e6e',
      green: '#67e480',
      yellow: '#e9f284',
      blue: '#78bfff',
      magenta: '#c58df5',
      cyan: '#67e4c8',
      white: '#e2dfe8',
      brightBlack: '#4a4a5a',
      brightRed: '#ff9999',
      brightGreen: '#9cf5b0',
      brightYellow: '#f5f9a0',
      brightBlue: '#aad4ff',
      brightMagenta: '#e0b8ff',
      brightCyan: '#9af5e4',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    accent: '#bb9af7',
    description: 'Deep blue city lights',
    xterm: {
      background: '#1a1b2e',
      foreground: '#a9b1d6',
      cursor: '#bb9af7',
      cursorAccent: '#1a1b2e',
      selectionBackground: 'rgba(187, 154, 247, 0.2)',
      selectionForeground: '#ffffff',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#ff899d',
      brightGreen: '#b9f27c',
      brightYellow: '#ff9e64',
      brightBlue: '#7da6ff',
      brightMagenta: '#c0abf5',
      brightCyan: '#a1e8ff',
      brightWhite: '#c0caf5',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    accent: '#cba6f7',
    description: 'Soothing pastel tones',
    xterm: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      cursorAccent: '#1e1e2e',
      selectionBackground: 'rgba(203, 166, 247, 0.2)',
      selectionForeground: '#1e1e2e',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#cba6f7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#cba6f7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    accent: '#bd93f9',
    description: 'Dark purple classic',
    xterm: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#bd93f9',
      cursorAccent: '#282a36',
      selectionBackground: 'rgba(189, 147, 249, 0.2)',
      selectionForeground: '#ffffff',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#6272a4',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    accent: '#88c0d0',
    description: 'Arctic cool blues',
    xterm: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#88c0d0',
      cursorAccent: '#2e3440',
      selectionBackground: 'rgba(136, 192, 208, 0.25)',
      selectionForeground: '#2e3440',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    accent: '#fe8019',
    description: 'Warm retro earthy tones',
    xterm: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#fe8019',
      cursorAccent: '#282828',
      selectionBackground: 'rgba(254, 128, 25, 0.2)',
      selectionForeground: '#282828',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    accent: '#528bff',
    description: 'Classic VS Code dark',
    xterm: {
      background: '#282c34',
      foreground: '#abb2bf',
      cursor: '#528bff',
      cursorAccent: '#282c34',
      selectionBackground: 'rgba(82, 139, 255, 0.2)',
      selectionForeground: '#ffffff',
      black: '#3f4451',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#d7dae0',
      brightBlack: '#4f5666',
      brightRed: '#ff616e',
      brightGreen: '#a5e075',
      brightYellow: '#f0a45d',
      brightBlue: '#4dc4ff',
      brightMagenta: '#de73ff',
      brightCyan: '#4cd1e0',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    accent: '#f97e72',
    description: 'Neon retro 80s vibes',
    xterm: {
      background: '#1a0937',
      foreground: '#f3eff5',
      cursor: '#f97e72',
      cursorAccent: '#1a0937',
      selectionBackground: 'rgba(249, 126, 114, 0.25)',
      selectionForeground: '#ffffff',
      black: '#2b1162',
      red: '#f97e72',
      green: '#72f1b8',
      yellow: '#fede5d',
      blue: '#36f9f6',
      magenta: '#ff7edb',
      cyan: '#36f9f6',
      white: '#f3eff5',
      brightBlack: '#5c4e8a',
      brightRed: '#fe4450',
      brightGreen: '#72f1b8',
      brightYellow: '#ffd400',
      brightBlue: '#36f9f6',
      brightMagenta: '#ff7edb',
      brightCyan: '#a3ebff',
      brightWhite: '#ffffff',
    },
  },
];

export const DEFAULT_THEME_ID = 'termimate-dark';

export function getTheme(id: string): TerminalTheme {
  return TERMINAL_THEMES.find((t) => t.id === id) ?? TERMINAL_THEMES[0];
}
